### ISSUE TITLE
using deepseek problem

### ISSUE THREAD

**Issue by wuhq7** [Canner/WrenAI#1305]
Referred to the example in this place（https://github.com/Canner/WrenAI/blob/main/wren-ai-service/docs/config_examples/config.deepseek.yaml）, and modified the pipeline configuration of 0.15.3, please help to see where there is a problem that needs to be modified

[config.txt](https://github.com/user-attachments/files/18808981/config.txt)

[env.txt](https://github.com/user-attachments/files/18808984/env.txt)

[wrenai-wren-ai-service-1.txt](https://github.com/user-attachments/files/18808985/wrenai-wren-ai-service-1.txt)

**Comment by wmywbyt2** [comment]
请问解决了么

**Comment by jos666** [comment]
1. embedder 配置要修改  deepseek 没有embedder 模型(本地部署 nomic-embed-text 模型)
```bash
#运行ollama server
OLLAMA_HOST="0.0.0.0" #设置这个环境变量
ollama pull nomic-embed-text
ollama serve
```
```yaml
type: embedder
provider: litellm_embedder
models:
- model: openai/nomic-embed-text  # put your embedding model name here, if it is not openai embedding model, should be <provider>/<model_name>
  api_base: http://192.168.1.88:11434/v1  # change this according to your embedding model    
  #api_key_name: EMBEDDER_OLLAMA_API_KEY
  api_key_name: OPENAI_API_KEY
  timeout: 600
```
2.  `type: document_store` 的 embedding_model_dim 修改为 768
3. deepseek 官方的api限流经常503体验不好
