### ISSUE TITLE
ollama embedding api

### ISSUE THREAD

**Issue by lsky-walt** [Canner/WrenAI#1319]
**Describe the bug**
**/api/embeddings** Ollama returns 404

**Screenshots**

![Image](https://github.com/user-attachments/assets/e3c34f81-d89e-4355-8237-18cf1f6d61a0)

![Image](https://github.com/user-attachments/assets/dc5d4686-c795-457e-a55a-50a195432584)

![Image](https://github.com/user-attachments/assets/030e85ac-4578-4796-afbd-6a61989e0e8a)

![Image](https://github.com/user-attachments/assets/4311b952-9dfa-415f-aa95-79ea69172595)

![Image](https://github.com/user-attachments/assets/2be49b54-62ce-4ced-a8ef-d4e35a1572e5)

**Desktop (please complete the following information):**
- OS: macos
- Browser chrome

**Wren AI Information**
- Version: 0.15.3

**Comment by jos666** [comment]
try this config
```yaml
type: embedder
provider: litellm_embedder
models:
- model: openai/nomic-embed-text  # put your embedding model name here, if it is not openai embedding model, should be <provider>/<model_name>
  api_base: http://localhost:11434/v1  # change this according to your embedding model
  api_key_name: OPENAI_API_KEY  # chang OPENAI_API_KEY   to random
  timeout: 600
---
type: document_store
provider: qdrant
location: http://qdrant:6333
embedding_model_dim: 768  # put your embedding model dimension here 
timeout: 120
recreate_index: true

```
