### ISSUE TITLE
KeyError 'SQL_explanation' when using Ollama

### ISSUE THREAD

**Issue by jfwreinhardt** [Canner/WrenAI#1333]
**Describe the bug**
wren-ai-service fails to start properly after setting api_base and model to use Ollama in config.yaml.  The startup status hangs on "UI service is ready".  Attempts to ask the prebuilt questions based on the e-commerce sample, results in the UI hanging and never returning an answer.  

**To Reproduce**

1. Run wren-launcher-linux
2. When asked to select an LLM provider, choose custom
3. Install will terminate so that you can create your custom config files
4. Visit the following github site, and use the .yaml file example to create your config.yaml.  Replace "host.docker.internal" with the IP or hostname of your local Ollama server.  Make sure you did an ollama pull phi4:14b and ollama pull nomic-embed-text so that the models referenced in the config.yaml file are available
https://github.com/Canner/WrenAI/blob/main/wren-ai-service/docs/config_examples/config.ollama.yaml
6. Update your .env files to make sure that the keys are set to random strings
8. Re-run wren-launcher-linux, it will pick up the newly create config files, pull down the components, and then attempt to start the services.  

**Expected behavior**
It was expected that wren components would start without errors, and the user could use the prebuilt e-commerce example from the UI.  

**Screenshots**

![Image](https://github.com/user-attachments/assets/41c54aa4-cf2d-4eec-841d-e96153095eb6)

![Image](https://github.com/user-attachments/assets/2418a14e-1d51-4cc9-9c02-40d1175fb862)

![Image](https://github.com/user-attachments/assets/282e6b99-6d19-489e-977b-d42510c239c5)

**Desktop (please complete the following information):**
root@ubuntu22server:~# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.5 LTS
Release:        22.04
Codename:       jammy

root@ubuntu22server:~# docker --version
Docker version 28.0.0, build f9ced58

**Wren AI Information**

![Image](https://github.com/user-attachments/assets/aaf3112f-0813-4546-a7f5-bd52b801586d)

![Image](https://github.com/user-attachments/assets/2dc69c1a-bd29-4fdf-99f7-e34bd08bf120)

**Relevant log output**
- Sharing .env
root@ubuntu22server:~/.wrenai# cat .env
COMPOSE_PROJECT_NAME=wrenai
PLATFORM=linux/amd64

PROJECT_DIR=/root/.wrenai

# service port
WREN_ENGINE_PORT=8080
WREN_ENGINE_SQL_PORT=7432
WREN_AI_SERVICE_PORT=5555
WREN_UI_PORT=3000
IBIS_SERVER_PORT=8000
WREN_UI_ENDPOINT=http://wren-ui:${WREN_UI_PORT}

# ai service settings
QDRANT_HOST=qdrant
SHOULD_FORCE_DEPLOY=1

# vendor keys
LLM_OPENAI_API_KEY=randomstring
EMBEDDER_OPENAI_API_KEY=randomstring
LLM_AZURE_OPENAI_API_KEY=randomstring
EMBEDDER_AZURE_OPENAI_API_KEY=randomstring
QDRANT_API_KEY=randomstring
LLM_OLLAMA_API_KEY=randomstring
EMBEDDER_OLLAMA_API_KEY=randomstring
OPENAI_API_KEY=randomstring

# version
# CHANGE THIS TO THE LATEST VERSION
WREN_PRODUCT_VERSION=0.15.3
WREN_ENGINE_VERSION=0.13.1
WREN_AI_SERVICE_VERSION=0.15.7
IBIS_SERVER_VERSION=0.13.1
WREN_UI_VERSION=0.20.1
WREN_BOOTSTRAP_VERSION=0.1.5

# user id (uuid v4)
USER_UUID=bdb3e260-6008-4e96-a2c1-2c3b447094a2

# for other services
POSTHOG_API_KEY=phc_nhF32aj4xHXOZb0oqr2cn4Oy9uiWzz6CCP4KZmRq9aE
POSTHOG_HOST=https://app.posthog.com
TELEMETRY_ENABLED=true
# this is for telemetry to know the model, i think ai-service might be able to provide a endpoint to get the information
GENERATION_MODEL=gpt-4o-mini
LANGFUSE_SECRET_KEY=
LANGFUSE_PUBLIC_KEY=

# the port exposes to the host
# OPTIONAL: change the port if you have a conflict
HOST_PORT=3000
AI_SERVICE_FORWARD_PORT=5555

# Wren UI
EXPERIMENTAL_ENGINE_RUST_VERSION=false

- Please share `config.yaml` with us, it should be located at `~/.wrenai/config.yaml`.
root@ubuntu22server:~/.wrenai# cat config.yaml
# you should rename this file to config.yaml and put it in ~/.wrenai
# please pay attention to the comments starting with # and adjust the config accordingly, 3 steps basically:
# 1. you need to use your own llm and embedding models
# 2. you need to use the correct pipe definitions based on https://raw.githubusercontent.com/canner/WrenAI/<WRENAI_VERSION_NUMBER>/docker/config.example.yaml
# 3. you need to fill in correct llm and embedding models in the pipe definitions

type: llm
provider: litellm_llm
models:
# put OPENAI_API_KEY=<random_string> in ~/.wrenai/.env
- api_base: http://192.168.8.213:11434/v1  # change this to your ollama host, api_base should be <ollama_url>/v1
  model: openai/phi4:14b  # openai/<ollama_model_name>
  timeout: 600
  kwargs:
    n: 1
    temperature: 0

---
type: embedder
provider: litellm_embedder
models:
# put OPENAI_API_KEY=<random_string> in ~/.wrenai/.env
- model: openai/nomic-embed-text  # put your ollama embedder model name here, openai/<ollama_model_name>
  api_base: http://192.168.8.213:11434/v1  # change this to your ollama host, api_base should be <ollama_url>/v1
  timeout: 600

---
type: engine
provider: wren_ui
endpoint: http://wren-ui:3000

---
type: document_store
provider: qdrant
location: http://qdrant:6333
embedding_model_dim: 768  # put your embedding model dimension here
timeout: 120
recreate_index: true

---
# please change the llm and embedder names to the ones you want to use
# the format of llm and embedder should be <provider>.<model_name> such as litellm_llm.gpt-4o-2024-08-06
# the pipes may be not the latest version, please refer to the latest version: https://raw.githubusercontent.com/canner/WrenAI/<WRENAI_VERSION_NUMBER>/docker/config.example.yaml
type: pipeline
pipes:
  - name: db_schema_indexing
    embedder: litellm_embedder.openai/nomic-embed-text
    document_store: qdrant
  - name: historical_question_indexing
    embedder: litellm_embedder.openai/nomic-embed-text
    document_store: qdrant
  - name: table_description_indexing
    embedder: litellm_embedder.openai/nomic-embed-text
    document_store: qdrant
  - name: db_schema_retrieval
    llm: litellm_llm.openai/phi4:14b
    embedder: litellm_embedder.openai/nomic-embed-text
    document_store: qdrant
  - name: historical_question_retrieval
    embedder: litellm_embedder.openai/nomic-embed-text
    document_store: qdrant
  - name: sql_generation
    llm: litellm_llm.openai/phi4:14b
    engine: wren_ui
  - name: sql_correction
    llm: litellm_llm.openai/phi4:14b
    engine: wren_ui
  - name: followup_sql_generation
    llm: litellm_llm.openai/phi4:14b
    engine: wren_ui
  - name: sql_summary
    llm: litellm_llm.openai/phi4:14b
  - name: sql_answer
    llm: litellm_llm.openai/phi4:14b
    engine: wren_ui
  - name: sql_breakdown
    llm: litellm_llm.openai/phi4:14b
    engine: wren_ui
  - name: sql_expansion
    llm: litellm_llm.openai/phi4:14b
    engine: wren_ui
  - name: semantics_description
    llm: litellm_llm.openai/phi4:14b
  - name: relationship_recommendation
    llm: litellm_llm.openai/phi4:14b
    engine: wren_ui
  - name: question_recommendation
    llm: litellm_llm.openai/phi4:14b
  - name: question_recommendation_db_schema_retrieval
    llm: litellm_llm.openai/phi4:14b
    embedder: litellm_embedder.openai/nomic-embed-text
    document_store: qdrant
  - name: question_recommendation_sql_generation
    llm: litellm_llm.openai/phi4:14b
    engine: wren_ui
  - name: chart_generation
    llm: litellm_llm.openai/phi4:14b
  - name: chart_adjustment
    llm: litellm_llm.openai/phi4:14b
  - name: intent_classification
    llm: litellm_llm.openai/phi4:14b
    embedder: litellm_embedder.openai/nomic-embed-text
    document_store: qdrant
  - name: data_assistance
    llm: litellm_llm.openai/phi4:14b
  - name: sql_pairs_indexing
    document_store: qdrant
    embedder: litellm_embedder.openai/nomic-embed-text
  - name: sql_pairs_retrieval
    document_store: qdrant
    embedder: litellm_embedder.openai/nomic-embed-text
    llm: litellm_llm.openai/phi4:14b
  - name: preprocess_sql_data
    llm: litellm_llm.openai/phi4:14b
  - name: sql_executor
    engine: wren_ui
  - name: sql_question_generation
    llm: litellm_llm.openai/phi4:14b
  - name: sql_generation_reasoning
    llm: litellm_llm.openai/phi4:14b
  - name: sql_regeneration
    llm: litellm_llm.openai/phi4:14b
    engine: wren_ui

---
settings:
  column_indexing_batch_size: 50
  table_retrieval_size: 10
  table_column_retrieval_size: 100
  allow_using_db_schemas_without_pruning: false  # if you want to use db schemas without pruning, set this to true. It will be faster
  query_cache_maxsize: 1000
  query_cache_ttl: 3600
  langfuse_host: https://cloud.langfuse.com
  langfuse_enable: true
  logging_level: DEBUG
  development: true

[wrenai-wren-engine.log](https://github.com/user-attachments/files/18951025/wrenai-wren-engine.log)
[wrenai-wren-ai-service.log](https://github.com/user-attachments/files/18951026/wrenai-wren-ai-service.log)
[wrenai-wren-ui.log](https://github.com/user-attachments/files/18951024/wrenai-wren-ui.log)
[wrenai-ibis-server.log](https://github.com/user-attachments/files/18951023/wrenai-ibis-server.log)

**Comment by paopa** [comment]
Hello @jfwreinhardt, thanks for bringing this up. Could you please add the following setting in the pipeline section in your config.yaml?

```
  - name: sql_explanation
    llm: litellm_llm.openai/phi4:14b
```

The issue arises because we removed the pipeline from the main branch and also updated the config example, but we haven’t released the new version yet. Therefore, in 0.15.3, the pipeline still requires this setting.

**Comment by jfwreinhardt** [comment]
Your suggestion appears to have resolved the "sql_explanation" error.  However, I then received a similar error for "sql_pairs_deletion".  I attempted to use a similar fix, by adding it to config.yaml, but the service still won't start properly.

**From my config.yaml**
```
  - name: sql_executor
    engine: wren_ui
  - name: sql_question_generation
    llm: litellm_llm.openai/phi4:14b
  - name: sql_generation_reasoning
    llm: litellm_llm.openai/phi4:14b
  - name: sql_regeneration
    llm: litellm_llm.openai/phi4:14b
    engine: wren_ui
  - name: sql_explanation
    llm: litellm_llm.openai/phi4:14b
  - name: sql_pairs_deletion
    llm: litellm_llm.openai/phi4:14b
```

**Logs attached**
[wrenai-wren-ui.log](https://github.com/user-attachments/files/18971692/wrenai-wren-ui.log)
[wrenai-wren-engine.log](https://github.com/user-attachments/files/18971694/wrenai-wren-engine.log)
[wrenai-wren-ai-service.log](https://github.com/user-attachments/files/18971691/wrenai-wren-ai-service.log)
[wrenai-ibis-server.log](https://github.com/user-attachments/files/18971693/wrenai-ibis-server.log)

**Comment by jfwreinhardt** [comment]
I looked through older config.yaml files and tried the following, but this resulted in new errors shown below

config.yaml snippet
```
  - name: sql_pairs_indexing
    document_store: qdrant
    embedder: litellm_embedder.openai/nomic-embed-text
  - name: sql_pairs_retrieval
    document_store: qdrant
    embedder: litellm_embedder.openai/nomic-embed-text
    llm: litellm_llm.openai/phi4:14b
  - name: preprocess_sql_data
    llm: litellm_llm.openai/phi4:14b
  - name: sql_executor
    engine: wren_ui
  - name: sql_question_generation
    llm: litellm_llm.openai/phi4:14b
  - name: sql_generation_reasoning
    llm: litellm_llm.openai/phi4:14b
  - name: sql_regeneration
    llm: litellm_llm.openai/phi4:14b
    engine: wren_ui
  - name: sql_explanation
    llm: litellm_llm.openai/phi4:14b
  - name: sql_pairs_deletion
    document_store: qdrant
    embedder: litellm_embedder.openai/nomic-embed-text
```

New error in the logs
```
Calculating embeddings: 100%|██████████| 1/1 [00:01<00:00,  1.83s/it]
Calculating embeddings: 100%|██████████| 1/1 [00:01<00:00,  1.83s/it]
********************************************************************************
> clean [src.pipelines.indexing.db_schema.clean()] encountered an error        <
> Node inputs:
{'cleaner': '<src.pipelines.indexing.DocumentCleaner object at ...',
 'embedding': "<Task finished name='Task-11' coro=<AsyncGraphAdap...",
 'project_id': None}
********************************************************************************
Traceback (most recent call last):
  File "/app/.venv/lib/python3.12/site-packages/hamilton/async_driver.py", line 122, in new_fn
    await fn(**fn_kwargs) if asyncio.iscoroutinefunction(fn) else fn(**fn_kwargs)
    ^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/langfuse/decorators/langfuse_decorator.py", line 219, in async_wrapper
    self._handle_exception(observation, e)
  File "/app/.venv/lib/python3.12/site-packages/langfuse/decorators/langfuse_decorator.py", line 517, in _handle_exception
    raise e
  File "/app/.venv/lib/python3.12/site-packages/langfuse/decorators/langfuse_decorator.py", line 217, in async_wrapper
    result = await func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/src/pipelines/indexing/db_schema.py", line 321, in clean
    await cleaner.run(project_id=project_id)
  File "/src/pipelines/indexing/__init__.py", line 45, in run
    await asyncio.gather(
  File "/src/pipelines/indexing/__init__.py", line 30, in _clear_documents
    store.to_dict().get("init_parameters", {}).get("index", "unknown")
    ^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/haystack_integrations/document_stores/qdrant/document_store.py", line 427, in to_dict
    init_params["api_key"] = self.api_key.to_dict() if self.api_key else None
                             ^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/haystack/utils/auth.py", line 84, in to_dict
    inner = self._to_dict()
            ^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/haystack/utils/auth.py", line 150, in _to_dict
    raise ValueError(
ValueError: Cannot serialize token-based secret. Use an alternative secret type like environment variables.
-------------------------------------------------------------------
Oh no an error! Need help with Hamilton?
Join our slack and ask for help! https://join.slack.com/t/hamilton-opensource/shared_invite/zt-2niepkra8-DGKGf_tTYhXuJWBTXtIs4g
-------------------------------------------------------------------
```

**Comment by paopa** [comment]
Hello @jfwreinhardt, this problem is caused by the need for an API key for Qdrant, and it cannot serialize it. I also noticed that your env file has the value `QDRANT_API_KEY=randomstring`. Try removing the value and starting again.

**Comment by jos666** [comment]
put `OPENAI_API_KEY=<random_string>` in ~/.wrenai/.env

**Comment by jfwreinhardt** [comment]
Commenting out the QDRANT value fixed it.  Attaching the final ".env" and "config.yaml" files for anyone else that's trying to get this running.

**Version info**
Wren AI 0.15.3
wren-ui:0.20.1 
wren-ai-service:0.15.7
wren-engine:0.13.1 
qdrant:v1.11.0 
wren-engine-ibis:0.13.1
wren-launcher-linux (md5sum=881f6bfb627011d08509703cfcbc3750)
Docker version 28.0.0, build f9ced58
Ollama 0.5.7
phi4:14b (ID=ac896e5b8b34)
nomic-embed-text (ID=0a109f422b47)

**Config files**

.env
```
COMPOSE_PROJECT_NAME=wrenai
PLATFORM=linux/amd64

PROJECT_DIR=/root/.wrenai

# service port
WREN_ENGINE_PORT=8080
WREN_ENGINE_SQL_PORT=7432
WREN_AI_SERVICE_PORT=5555
WREN_UI_PORT=3000
IBIS_SERVER_PORT=8000
WREN_UI_ENDPOINT=http://wren-ui:${WREN_UI_PORT}

# ai service settings
QDRANT_HOST=qdrant
SHOULD_FORCE_DEPLOY=1

# vendor keys
LLM_OPENAI_API_KEY=randomstring
EMBEDDER_OPENAI_API_KEY=randomstring
LLM_AZURE_OPENAI_API_KEY=randomstring
EMBEDDER_AZURE_OPENAI_API_KEY=randomstring
# QDRANT_API_KEY=randomstring
LLM_OLLAMA_API_KEY=randomstring
EMBEDDER_OLLAMA_API_KEY=randomstring
OPENAI_API_KEY=randomstring

# version
# CHANGE THIS TO THE LATEST VERSION
WREN_PRODUCT_VERSION=0.15.3
WREN_ENGINE_VERSION=0.13.1
WREN_AI_SERVICE_VERSION=0.15.7
IBIS_SERVER_VERSION=0.13.1
WREN_UI_VERSION=0.20.1
WREN_BOOTSTRAP_VERSION=0.1.5

# user id (uuid v4)
USER_UUID=bdb3e260-6008-4e96-a2c1-2c3b447094a2

# for other services
POSTHOG_API_KEY=phc_nhF32aj4xHXOZb0oqr2cn4Oy9uiWzz6CCP4KZmRq9aE
POSTHOG_HOST=https://app.posthog.com
TELEMETRY_ENABLED=true
# this is for telemetry to know the model, i think ai-service might be able to provide a endpoint to get the information
GENERATION_MODEL=gpt-4o-mini
LANGFUSE_SECRET_KEY=
LANGFUSE_PUBLIC_KEY=

# the port exposes to the host
# OPTIONAL: change the port if you have a conflict
HOST_PORT=3000
AI_SERVICE_FORWARD_PORT=5555

# Wren UI
EXPERIMENTAL_ENGINE_RUST_VERSION=false
```

config.yaml
```
# you should rename this file to config.yaml and put it in ~/.wrenai
# please pay attention to the comments starting with # and adjust the config accordingly, 3 steps basically:
# 1. you need to use your own llm and embedding models
# 2. you need to use the correct pipe definitions based on https://raw.githubusercontent.com/canner/WrenAI/<WRENAI_VERSION_NUMBER>/docker/config.example.yaml
# 3. you need to fill in correct llm and embedding models in the pipe definitions

type: llm
provider: litellm_llm
models:
# put OPENAI_API_KEY=<random_string> in ~/.wrenai/.env
- api_base: http://192.168.8.213:11434/v1  # change this to your ollama host, api_base should be <ollama_url>/v1
  model: openai/phi4:14b  # openai/<ollama_model_name>
  timeout: 600
  kwargs:
    n: 1
    temperature: 0

---
type: embedder
provider: litellm_embedder
models:
# put OPENAI_API_KEY=<random_string> in ~/.wrenai/.env
- model: openai/nomic-embed-text  # put your ollama embedder model name here, openai/<ollama_model_name>
  api_base: http://192.168.8.213:11434/v1  # change this to your ollama host, api_base should be <ollama_url>/v1
  timeout: 600

---
type: engine
provider: wren_ui
endpoint: http://wren-ui:3000

---
type: document_store
provider: qdrant
location: http://qdrant:6333
embedding_model_dim: 768  # put your embedding model dimension here
timeout: 120
recreate_index: true

---
# please change the llm and embedder names to the ones you want to use
# the format of llm and embedder should be <provider>.<model_name> such as litellm_llm.gpt-4o-2024-08-06
# the pipes may be not the latest version, please refer to the latest version: https://raw.githubusercontent.com/canner/WrenAI/<WRENAI_VERSION_NUMBER>/docker/config.example.yaml
type: pipeline
pipes:
  - name: db_schema_indexing
    embedder: litellm_embedder.openai/nomic-embed-text
    document_store: qdrant
  - name: historical_question_indexing
    embedder: litellm_embedder.openai/nomic-embed-text
    document_store: qdrant
  - name: table_description_indexing
    embedder: litellm_embedder.openai/nomic-embed-text
    document_store: qdrant
  - name: db_schema_retrieval
    llm: litellm_llm.openai/phi4:14b
    embedder: litellm_embedder.openai/nomic-embed-text
    document_store: qdrant
  - name: historical_question_retrieval
    embedder: litellm_embedder.openai/nomic-embed-text
    document_store: qdrant
  - name: sql_generation
    llm: litellm_llm.openai/phi4:14b
    engine: wren_ui
  - name: sql_correction
    llm: litellm_llm.openai/phi4:14b
    engine: wren_ui
  - name: followup_sql_generation
    llm: litellm_llm.openai/phi4:14b
    engine: wren_ui
  - name: sql_summary
    llm: litellm_llm.openai/phi4:14b
  - name: sql_answer
    llm: litellm_llm.openai/phi4:14b
    engine: wren_ui
  - name: sql_breakdown
    llm: litellm_llm.openai/phi4:14b
    engine: wren_ui
  - name: sql_expansion
    llm: litellm_llm.openai/phi4:14b
    engine: wren_ui
  - name: semantics_description
    llm: litellm_llm.openai/phi4:14b
  - name: relationship_recommendation
    llm: litellm_llm.openai/phi4:14b
    engine: wren_ui
  - name: question_recommendation
    llm: litellm_llm.openai/phi4:14b
  - name: question_recommendation_db_schema_retrieval
    llm: litellm_llm.openai/phi4:14b
    embedder: litellm_embedder.openai/nomic-embed-text
    document_store: qdrant
  - name: question_recommendation_sql_generation
    llm: litellm_llm.openai/phi4:14b
    engine: wren_ui
  - name: chart_generation
    llm: litellm_llm.openai/phi4:14b
  - name: chart_adjustment
    llm: litellm_llm.openai/phi4:14b
  - name: intent_classification
    llm: litellm_llm.openai/phi4:14b
    embedder: litellm_embedder.openai/nomic-embed-text
    document_store: qdrant
  - name: data_assistance
    llm: litellm_llm.openai/phi4:14b
  - name: sql_pairs_indexing
    document_store: qdrant
    embedder: litellm_embedder.openai/nomic-embed-text
  - name: sql_pairs_retrieval
    document_store: qdrant
    embedder: litellm_embedder.openai/nomic-embed-text
    llm: litellm_llm.openai/phi4:14b
  - name: preprocess_sql_data
    llm: litellm_llm.openai/phi4:14b
  - name: sql_executor
    engine: wren_ui
  - name: sql_question_generation
    llm: litellm_llm.openai/phi4:14b
  - name: sql_generation_reasoning
    llm: litellm_llm.openai/phi4:14b
  - name: sql_regeneration
    llm: litellm_llm.openai/phi4:14b
    engine: wren_ui
  - name: sql_explanation
    llm: litellm_llm.openai/phi4:14b
  - name: sql_pairs_deletion
    document_store: qdrant
    embedder: litellm_embedder.openai/nomic-embed-text

---
settings:
  column_indexing_batch_size: 50
  table_retrieval_size: 10
  table_column_retrieval_size: 100
  allow_using_db_schemas_without_pruning: false  # if you want to use db schemas without pruning, set this to true. It will be faster
  query_cache_maxsize: 1000
  query_cache_ttl: 3600
  langfuse_host: https://cloud.langfuse.com
  langfuse_enable: true
  logging_level: DEBUG
  development: true
```
