### ISSUE TITLE
Failed to deploy. Please check the log for more details.

### ISSUE THREAD

**Issue by sijianzheng** [Canner/WrenAI#1342]
**Describe the bug**
I wanna use Ollama with WrenAi and followed the tutorial in the [How to use your preferred LLM, Embedder or Document Store in Wren AI](https://docs.getwren.ai/oss/installation/custom_llm#running-wren-ai-with-your-custom-llm-embedder) and modified my .env and config.yaml files. I was able to launch Wren Ai normally using my browser but "failed to deploy". 

**Desktop (please complete the following information):**
- OS: Windows 11
- Browser: Edge

**Wren AI Information**
- Version: 0.15.3

**Relevant log output**
[config.txt](https://github.com/user-attachments/files/19002482/config.txt)
[.env.txt](https://github.com/user-attachments/files/19002496/default.env.txt)
[wrenai-wren-ui.log](https://github.com/user-attachments/files/19002583/wrenai-wren-ui.log)
[wrenai-wren-ai-service.log](https://github.com/user-attachments/files/19002590/wrenai-wren-ai-service.log)
[wrenai-wren-engine.log](https://github.com/user-attachments/files/19002603/wrenai-wren-engine.log)
[wrenai-ibis-server.log](https://github.com/user-attachments/files/19002626/wrenai-ibis-server.log)

**Comment by paopa** [comment]
Hi @sijianzheng, I noticed you don’t change the pipeline setting for llm and embedder in config.yaml.

e.g.

```yaml
  - name: db_schema_retrieval
    llm: litellm_llm.openai/deepseek-r1:8b
    embedder: litellm_embedder.openai/nomic-embed-text
    document_store: qdrant
```
