### ISSUE TITLE
Data privacy mode

### ISSUE THREAD

**Issue by ratuldawar11** [Canner/WrenAI#1532]
Wren AI sends data to the LLM provider in multiple places, this leads do data privacy issues since many organisations don't want to send their data to OpenAi, google etc. 

Potential solution: 
We should consider adding a `include_sql_data_in_prompt` so that users can choose if they want to send data to the LLM provider or not. 
Willing to work on this feature, wanted to understand if this is aligned with the product roadmap ?

**Comment by cyyeh** [comment]
@ratuldawar11 what you suggest is users can change the value of `include_sql_data_in_prompt` in config.yaml right? maybe you could add a new entry in the settings section sth like this:

```
settings:
  allow_intent_classification: true
  allow_sql_generation_reasoning: true
  allow_using_db_schemas_without_pruning: true
  ...
  include_sql_data_in_prompt: true
```
