### ISSUE TITLE
The response language is not aligned with the project settings.

### ISSUE THREAD

**Issue by wirelessr** [Canner/WrenAI#1550]
**Describe the bug**
My project is set to English, but the suggested questions are in a language I don’t recognize.

For example,
1. ¿Cuántos departamentos tienen un nombre que comience con la letra 'M'?
2. ¿Qué es el título actual del empleado con emp_no = 10001?

**To Reproduce**
After initializing, wait and see.

**Expected behavior**
Useful or not, the recommendations should at least be in English.

**Screenshots**

![Image](https://github.com/user-attachments/assets/8fdf6ef8-bb7d-4159-9ee7-074b5190bf0c)

**Desktop (please complete the following information):**
- OS: Mac
- Browser: Chrome

**Wren AI Information**
- Version: 0.19.1

**Additional context**

**Relevant log output**
```yaml
type: llm
provider: litellm_llm
timeout: 120
models:
  - model: ollama_chat/llama3.1:8b
    alias: default
    api_base: http://host.docker.internal:11434
    kwargs:
      temperature: 0
      n: 1
      seed: 0
      max_tokens: 4096

---
type: embedder
provider: litellm_embedder
models:
  - model: ollama/nomic-embed-text
    alias: default
    timeout: 120
    api_base: http://host.docker.internal:11434
```

The rest of the logs look normal.
