### ISSUE TITLE
Try to run on kubernetes Bootstrap not working 

### ISSUE THREAD

**Issue by didlawowo** [Canner/WrenAI#768]
**Describe the bug**
i trying to run wren ai on kubernetes using my own helm chart and get error with bootstrap on engine deployment. i have based my helm chart on analysis of your kustomize.

```
init config.properties
/app/init.sh: line 21: can't create "/app/data"/config.properties: nonexistent directory
grep: "/app/data"/config.properties: No such file or directory
wren.experimental-enable-dynamic-fields is not set, set it to true
/app/init.sh: line 29: can't create "/app/data"/config.properties: nonexistent directory
create mdl folder
mkdir: can't create directory '"/app/data"/mdl': No such file or directory
init mdl/sample.json
/app/init.sh: line 41: can't create "/app/data"/mdl/sample.json: nonexistent directory
init accounts file
/app/init.sh: line 49: can't create "/app/data"/accounts: nonexistent directory
Stream closed EOF for wren/wren-engine-678cf74cf9-8pdwf (bootstrap)
```

**To Reproduce**

just install init container 

```
    initContainers:
    - name: bootstrap
      image: ghcr.io/canner/wren-bootstrap:0.1.4
      env:
      - name: DATA_PATH
        valueFrom:
          configMapKeyRef:
            name: wren
            key: WREN_ENGINE_DATA_PATH
      - name: PG_PASSWORD
        valueFrom:
          secretKeyRef:
            name: wren-postgresql
            key: postgres-password
      - name: PG_USERNAME
        valueFrom:
          secretKeyRef:
            name: wren
            key: PG_USERNAME
      volumeMounts:
      - name: wren-data
        mountPath: /app/data
      command: ["/bin/sh", "/app/init.sh"]
```

**Expected behavior**
mount working and create file
 

 

**Additional context**

i can provide my helm chart on discord.
